FileVersion = 1
Dependencies = {corlib = "*", GLFW = "*", Ultralight = "*"}

[Project]
Name = "Ultralight-beef-samples"
TargetType = "BeefGUIApplication"
StartupObject = "UltralightBeefSamples.Program"
